name: lint, test, build
on: push
jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - name: get code
              uses: actions/checkouts@v3
            - name: install nodejs
              uses: actions/setup-node@v3
              with:
                node-version: 18
            - name: install dependencies
              run: npm ci
            - name: lint
              run: npm lint
    test:
        needs: lint
        runs-on: ubuntu-latest
        steps:
            - name: get code
              uses: actions/checkouts@v3
            - name: install nodejs
              uses: actions/setup-node@v3
              with:
                node-version: 18
            - name: install dependencies
              run: npm ci
            - name: test
              run: npm test
    build:
        needs: test
        runs-on: ubuntu-latest
        steps:
            - name: get code
              uses: actions/checkouts@v3
            - name: install nodejs
              uses: actions/setup-node@v3
              with:
                node-version: 18
            - name: install dependencies
              run: npm ci
            - name: build
              run: npm build
