name: list details about issues
on: issues
jobs:
    issue-info:
        runs-on: ubuntu-latest
        env:
            GITHUB_EVENT: ${{ toJson(github.event) }}
        steps:
            - name: print issue details
              run: echo $GIThub_EVENT
